image: debian:latest

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - bash -c "ssh-add <(echo '$SSH_PRIVATE_KEY')"
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  type: deploy
  environment:
    name: staging
    url: ai-arena.net
  script:
    - ssh aiarena@ai-arena.net -p 2281 "cd /home/aiarena/ai-arena/ && git checkout master && git pull origin master && git submodule update --init --recursive && source venv/bin/activate && python3 ./pip/pip-install.py && python3 manage.py test --no-input && /home/aiarena/cleardb.sh && python3 manage.py migrate && python3 manage.py seed --token=f082882006a216a22a797eeb3fc7c848da45ff8b && python3 manage.py collectstatic --noinput && python3 manage.py migrate && sudo apachectl graceful && exit"
  only:
    - master

deploy_production:
  type: deploy
  environment:
    name: production
    url: ai-arena.net
  when: manual
  script:
    - ssh aiarena@ai-arena.net -p 2280 "cd /home/aiarena/ai-arena/ && git checkout master && git pull origin master && git submodule update --init --recursive && source venv/bin/activate && python3 ./pip/pip-install.py && python3 manage.py collectstatic --noinput && python3 manage.py migrate && sudo apachectl graceful && exit"
  only:
    - master